# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - app-001-step3-1-suzuyu-py-42

on:
  push:
    branches:
      - main
    paths: # ★★★ 修正点1: backendディレクトリ内の変更があった場合のみワークフローをトリガー
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        # ★★★ 修正点2: backendディレクトリ内で仮想環境を作成
        working-directory: ./backend # backendディレクトリを作業ディレクトリに設定
        run: |
          python -m venv venv
          source venv/bin/activate
          
      - name: Install dependencies
        # ★★★ 修正点3: backendディレクトリ内で依存関係をインストール
        working-directory: ./backend # backendディレクトリを作業ディレクトリに設定
        run: pip install -r requirements.txt
          
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        # ★★★ 修正点4: backendディレクトリの内容のみをZIP化し、そのZIPファイルを親ディレクトリ（ジョブのルート）に作成
        working-directory: ./backend # backendディレクトリを作業ディレクトリに設定
        # backend内のファイルをZIP化し、ZIPファイル自体はbackendの親ディレクトリに置く
        run: zip -r ../release.zip ./* -x "venv/*" -x "__pycache__/*" -x "*.pyc"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          # ★★★ 修正点5: 親ディレクトリに作成したZIPファイルをアップロード
          path: release.zip # ジョブのルートにあるrelease.zipを指定
          # !venv/ はZIP作成時に除外済みのため、ここでは不要

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        # ★★★ 修正点6: ダウンロードしたZIPファイルを現在の作業ディレクトリに解凍
        run: unzip release.zip # 現在のディレクトリに解凍される

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'app-001-step3-1-suzuyu-py-42'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BE7A6E84BE1D4FB3A71965841F18E4E8 }}
          # ★★★ 修正点7: 解凍されたアプリケーションコンテンツがカレントディレクトリにあるため、'.' を指定
          package: '.' # 現在のディレクトリ全体をデプロイ対象とする
