# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - app-001-step3-1-suzuyu-py-42

on:
  push:
    branches:
      - main
    paths: # backendディレクトリ内の変更があった場合のみワークフローをトリガー
      - 'backend/**'
  workflow_dispatch:

jobs:
  build: # このビルドジョブは主に環境準備と依存関係のインストールをトリガーするためのもの（Oryxが担当）
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4 # リポジトリ全体をクローン

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      # ★★★ ここにあった仮想環境作成と依存関係インストールのステップは削除しました ★★★
      # これらの処理は、Oryx (enable-oryx-build: true) がデプロイ時に自動的に行います。
      # ここで手動で行うとOryxの処理と競合し、問題を引き起こす可能性がありました。

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      # ★★★ ここにあったZIP化とアーティファクトアップロードのステップも削除しました ★★★
      # Oryxが直接ソースディレクトリをZIP化してデプロイするため不要です。

  deploy:
    runs-on: ubuntu-latest
    needs: build # buildジョブが完了してから実行
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - uses: actions/checkout@v4 # ★★★ deployジョブでもコードをクローンする ★★★
                                 # deployジョブがbuildジョブの成果物に依存しないため、必須です。

      # ★★★ ここにあった成果物のダウンロードと解凍のステップは削除しました ★★★
      # package: './backend' でソースディレクトリを直接指定するため不要です。

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'app-001-step3-1-suzuyu-py-42'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BE7A6E84BE1D4FB3A71965841F18E4E8 }}
          # ★★★ リポジトリ内のbackendディレクトリを直接デプロイ対象とする ★★★
          package: './backend' 
          # ★★★ Oryxビルドを有効化し、Azure側で依存関係を自動インストールさせる ★★★
          enable-oryx-build: true 
          # ★★★ アプリケーションの仮想パスを明示的に指定 ★★★
          # Web Appのルートから見てbackendディレクトリがアプリのルートであることをOryxに伝える
          virtual-application: '/backend'
